[package]
name = "task-maker-format"
version = "0.5.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
task-maker-dag = { path = "../task-maker-dag" }
task-maker-lang = { path = "../task-maker-lang" }
task-maker-exec = { path = "../task-maker-exec" }

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
# Generic error utilities
anyhow = { version = "1.0", features = ["backtrace"] }
# General iterator utilities
itertools = "0.8"
# Utilities for writing to the terminal with colors
termcolor = "1"
# Logging
log = "0.4"
# Globbing files
glob = "0.2"
# Text parser for parsing the gen/GEN file
pest = "2.1"
pest_derive = "2.1"
# Curses UI
tui = "0.5"
termion = "1.5"
# Global constants
lazy_static = "1.3"
# Checking equalness between floats
approx = "0.3"
# Regular expressions
regex = "1"
# File templating (for building statement tex file)
askama = "0.8"
askama_derive = "0.8"
# Detecting the content type of a file
mime_guess = "2.0"
# Geenrating random numbers (the seed in terry)
rand = "0.7"
# Split command line arguments
shell-words = "0.1"
# Nicer derive macros
derivative = "2.1"
# For sending ^C to the process
nix = "0.17"
# Typescript definition generation
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}

[dev-dependencies]
tempdir = "0.3"
pretty_assertions = "0.6"
# assert_that! macro
spectral = "0.6"