[package]
name = "task-maker-exec"
version = "0.5.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
task-maker-dag = { path = "../task-maker-dag" }
task-maker-store = { path = "../task-maker-store" }
task-maker-cache = { path = "../task-maker-cache" }

# Generic error utilities
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.1"
# Logging
log = "0.4"
# UUID generation
uuid = { version = "0.7", features = ["v4", "serde"] }
# Temporary directory for sandboxes and FIFO directory
tempdir = "0.3"
# Resolve executable names in $PATH
which = "2.0"
# General iterator utilities
itertools = "0.8"
# defer! macro
scopeguard = "1.0"
# Threadsafe hashmap
chashmap = "2.2"
# Sandbox
tabox = "1"
# For killing processes and making FIFOs
nix = "0.17"
# In-memory and remote channels
ductile = "0.2"
# Key Derivation Function from a password
scrypt = "0.3"
# Typescript definition generation
typescript-definitions = { git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs"}

[dev-dependencies]
pretty_assertions = "0.6"
env_logger = "0.6"